name: hiremi_version_two
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  icons_flutter: ^0.0.4
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  hexcolor: ^3.0.1
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  fan_carousel_image_slider: ^1.0.1
  carousel_slider: ^4.2.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - images/
    - images/icons/
  fonts:
    - family: FontMain
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/MyIcons.ttf